# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Design_add_form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(572, 405)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0, 350, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.idesc = QtWidgets.QPlainTextEdit(Form)
        self.idesc.setGeometry(QtCore.QRect(10, 250, 551, 91))
        self.idesc.setObjectName("idesc")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.iroast = QtWidgets.QComboBox(Form)
        self.iroast.setGeometry(QtCore.QRect(90, 60, 181, 22))
        self.iroast.setObjectName("iroast")
        self.iroast.addItem("")
        self.iroast.addItem("")
        self.iroast.addItem("")
        self.iroast.addItem("")
        self.iroast.addItem("")
        self.iroast.addItem("")
        self.iroast.addItem("")
        self.iroast.addItem("")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.icond = QtWidgets.QComboBox(Form)
        self.icond.setGeometry(QtCore.QRect(100, 100, 131, 22))
        self.icond.setObjectName("icond")
        self.icond.addItem("")
        self.icond.addItem("")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.iprice = QtWidgets.QSpinBox(Form)
        self.iprice.setGeometry(QtCore.QRect(60, 140, 101, 22))
        self.iprice.setMaximum(1000)
        self.iprice.setObjectName("iprice")
        self.isort = QtWidgets.QLineEdit(Form)
        self.isort.setGeometry(QtCore.QRect(140, 21, 171, 21))
        self.isort.setObjectName("isort")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ivol = QtWidgets.QSpinBox(Form)
        self.ivol.setGeometry(QtCore.QRect(70, 180, 91, 22))
        self.ivol.setMaximum(1000)
        self.ivol.setObjectName("ivol")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Готово"))
        self.label.setText(_translate("Form", "Описание:"))
        self.label_2.setText(_translate("Form", "Название сорта:"))
        self.label_3.setText(_translate("Form", "Обжарка:"))
        self.iroast.setItemText(0, _translate("Form", "Коричная"))
        self.iroast.setItemText(1, _translate("Form", "Новоанглийская"))
        self.iroast.setItemText(2, _translate("Form", "Американская "))
        self.iroast.setItemText(3, _translate("Form", "Городская"))
        self.iroast.setItemText(4, _translate("Form", "Полная городская"))
        self.iroast.setItemText(5, _translate("Form", "Венская "))
        self.iroast.setItemText(6, _translate("Form", "Французская "))
        self.iroast.setItemText(7, _translate("Form", "Испанская "))
        self.label_4.setText(_translate("Form", "Состояние:"))
        self.icond.setItemText(0, _translate("Form", "Зерновой"))
        self.icond.setItemText(1, _translate("Form", "Молотый"))
        self.label_5.setText(_translate("Form", "Цена:"))
        self.label_6.setText(_translate("Form", "Объем:"))
